// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Documentation",
            "url": "ig.pomazkov@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/mint_token": {
            "post": {
                "tags": [
                    "Mint"
                ],
                "summary": "Mint token",
                "parameters": [
                    {
                        "description": "mint structure",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/endpoints.mintReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Private key for signing tx",
                        "name": "Private-Key",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoints.mintResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "endpoints.mintReq": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "receiver": {
                    "type": "string"
                }
            }
        },
        "endpoints.mintResp": {
            "type": "object",
            "properties": {
                "tx_hash": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{"http"},
	Title:            "Mint internal API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
