consumes:
- application/json
definitions:
  endpoints.mintReq:
    properties:
      amount:
        type: string
      receiver:
        type: string
    type: object
  endpoints.mintResp:
    properties:
      tx_hash:
        type: string
    type: object
info:
  contact:
    name: API Documentation
    url: ig.pomazkov@gmail.com
  title: Mint internal API
  version: "1.0"
paths:
  /v1/mint_token:
    post:
      parameters:
      - description: mint structure
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/endpoints.mintReq'
      - description: Private key for signing tx
        in: header
        name: Private-Key
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/endpoints.mintResp'
      summary: Mint token
      tags:
      - Mint
produces:
- application/json
schemes:
- http
swagger: "2.0"
