name: Golang CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Display Go version
        run: go version

      - name: Go linter installation
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53

      - name: Update dependencies
        run: go mod tidy && go mod verify

      - name: Go linter run
        run: golangci-lint run


  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Display Go version
        run: go version

      - name: Install test lib
        run: go install gotest.tools/gotestsum@latest

      - name: Test
        run: gotestsum --format=testname -- ./... -tags=units,integrations -cover